import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Box, CardMedia } from "@mui/material";
import { useAppDispatch, useAppSelector } from "../src/Store";
import {
  selectProductItems,
  selectLoadingItems,
} from "../src/Store/Selectors/productSelectors";
import { getProductItems } from "../src/Store/Thunks/productThunks";
import { ProductItems } from "../src/Components/home-page/ProductItems";

import styles from "../styles/index.module.scss";
import { RecentlyViewed } from "../src/Components/home-page/RecentlyViewed";
import { ProductItemModel } from "../src/Store/Models/Product/ProductItem";

export default function Home() {
  const [isMounted, setIsMounted] = useState<boolean>(false);
  const [recentlyViewedItems, setRecentlyViewedItems] = useState<
    ProductItemModel[]
  >([]);

  const dispatch = useAppDispatch();

  const productItems = useAppSelector(selectProductItems);
  const loading = useAppSelector(selectLoadingItems);
  useEffect(() => {
    setIsMounted(true);
    if (isMounted && !productItems.length) {
      dispatch(getProductItems(""));
    }

    //eslint disable-next-line
  }, [isMounted]);

  useEffect(() => {
    setRecentlyViewedItems(
      JSON.parse(localStorage?.getItem("recentlyViewed") || "[]")
    );
  }, []);

  return (
    <>
      <Box className={styles.heroContainer}>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <CardMedia
            component="video"
            autoPlay
            loop
            muted
            src="/hero_video.mp4"
          />
        </div>
        <div className={styles.secondContainer}></div>
      </Box>

      <img src="/dropplets.webp" alt="" className={styles.dropplets} />
      <ProductItems />
      <div
        className={`${styles.divider} ${styles.div_transparent} ${styles.div_dot} `}
      >
        <span className={`${styles.div_dot_two}`}></span>
      </div>
      {recentlyViewedItems.length && (
        <>
          <RecentlyViewed items={recentlyViewedItems} />
          <div
            className={`${styles.divider} ${styles.div_transparent} ${styles.div_dot} `}
          >
            <span className={`${styles.div_dot_two}`}></span>
          </div>
        </>
      )}
    </>
  );
}
