import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Container, Paper, Grid, Box, CardMedia } from "@mui/material";

import { useAppDispatch, useAppSelector } from "../src/Store";

import {
  selectProductItems,
  selectLoadingItems,
} from "../src/Store/Selectors/productSelectors";
import Card from "../src/Components/card/Card";
import { getProductItems } from "../src/Store/Thunks/productThunks";

import styles from "../styles/index.module.scss";
import Image from "next/image";

export default function Home() {
  const [expand, setExpand] = useState<boolean>(true);
  const [containerIndex, setContainerIndex] = useState<number>(0);
  const [isMounted, setIsMounted] = useState<boolean>(false);

  const dispatch = useAppDispatch();

  const loading = useAppSelector(selectLoadingItems);

  const productItems = useAppSelector(selectProductItems);

  useEffect(() => {
    setIsMounted(true);
    if (isMounted && !productItems.length) {
      dispatch(getProductItems(""));
    }

    //eslint disable-next-line
  }, [isMounted]);

  return (
    <>
      <Box className={styles.heroContainer}>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <CardMedia
            component="video"
            autoPlay
            loop
            muted
            src="/hero_video.mp4"
          />
        </div>
        <div className={styles.secondContainer}></div>
      </Box>

      <img src="/dropplets.webp" alt="" className={styles.dropplets} />
      <Container className={styles.ProductsContainer} maxWidth="xl">
        <Box className={styles.categoryWrapper}>
          <Grid container rowGap={2}>
            {productItems?.map((card, index) => (
              <Grid
                key={card.productId}
                item
                xs={3}
                onMouseEnter={() => {
                  setExpand(true);
                  setContainerIndex(index);
                }}
                onMouseLeave={() => {
                  setExpand(false);
                }}
              >
                <Paper
                  sx={{
                    width: 300,
                    height: expand && containerIndex === index ? 550 : 500,
                    padding: 1,
                    transition: "all 0.5s ease",
                  }}
                  className={styles.cardContainer}
                  elevation={1}
                >
                  <Card
                    card={card}
                    expand={expand}
                    containerIndex={containerIndex}
                    index={index}
                  />
                </Paper>
              </Grid>
            ))}
          </Grid>
        </Box>
      </Container>
    </>
  );
}
