export const FruitItems = [
  { value: 1, label: "" },
  { value: 2, label: "Ananas" },
  { value: 3, label: "Aronia" },
  { value: 4, label: "Banane" },
  { value: 5, label: "Cocos" },
  { value: 6, label: "Cătină" },
  { value: 7, label: "Ghimbir" },
  { value: 8, label: "Goji" },
  { value: 9, label: "Lamaie" },
  { value: 10, label: "Mango" },
  { value: 11, label: "Merisor" },
  { value: 12, label: "Papaya" },
  { value: 13, label: "Mixt" },
  { value: 14, label: "Nucă" },
  { value: 15, label: "Migdale" },
  { value: 16, label: "Caju" },
];
